config/routes.rb
Rails.application.routes.draw do
	# HOMEPAGE
	root 'gossips#index'	

	# ROUTE TEAM & CONTACT
	get '/team', to: 'team#presentation'
	get '/contact', to: 'contact#affichage'

	# ROUTE DYNAMIC PATH
	get '/welcome/:first_name', to: 'welcome#show_welcome'    

	resources :gossips do
		resources :comments, except: [:show, :index]
	end

	resources :users
	resources :cities, except: [:update, :edit, :destroy, :create, :new]
	resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name, presence: true
	validates :zip_code, presence: true

	#LINK USER
	has_many :users
	#LINK GOSSIP
	has_many :gossips
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true

	#LINK USER
	belongs_to :user

	#LINK GOSSIP
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true
	validates :content, presence: true
	belongs_to :user

	#LINK CITY
	belongs_to :city, optional: true

	#LINK COMMENTS
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	#NAMES & AGE
	validates :first_name, presence: true
	validates :last_name, presence: true
	#EMAIL
	validates :email, presence: true,
		uniqueness: true
	#PASSWORD & BCRYPT
	has_secure_password
	validates :password, presence: true,
		length: {minimum: 6}
	#AGE
	validates :age, presence: true

	#LINK GOSSIP
	has_many :gossips
	#LINK CITY
	belongs_to :city, optional: true
	#LINK COMMENT
	has_many :comments
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
	  @cities_arr = City.all
  end

  def show
	  @city = City.find(params[:id])
	  puts "=" * 60
	  puts @city
	  puts params
	  puts "=" * 60
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticated, only: [:new, :edit]

	def new
		current_gossip = Gossip.find(params[:gossip_id])
		@comment = Comment.new(gossip: current_gossip)
	end

	def create
		comment_params = params[:comment]
		@comment = Comment.new
		@comment.user = current_user 
		@comment.content = comment_params[:content]
		@comment.gossip = Gossip.find(params[:gossip_id])
		@comment.save
		redirect_to gossip_path(@comment.gossip.id)
	end

	def edit
		puts '\n' + '=' * 25 + 'EDIT' + '=' * 25
		puts params
		puts '=' * 25 + 'EDIT' + '=' * 25 + '\n'
		current_gossip = Gossip.find(params[:gossip_id])
		@comment = Comment.find(params[:id]) 
	end

	def update
		puts "\n" + '=' * 25 + 'UPDATE' + '=' * 25
		puts params.inspect
		puts '=' * 25 + 'UPDATE' + '=' * 25 + "\n"
		@comment = Comment.find(params[:id])
		comment_params = params.require(:comment).permit(:content)
		@comment.update(comment_params)
		redirect_to(gossip_path(params[:gossip_id]))
	end

	private

	def authenticated
		unless current_user
			redirect_to new_session_path
		end
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

def affichage
  puts "AFFICHAGE"
end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	before_action :authenticated, except: [:index, :show]
	
	def index
		# DANS SERVEUR AFFICHAGE SESSIONS A CHAQUE RETOUR INDEX
		puts "=" * 25 + 'INDEX' + "=" * 25
		puts "SESSION == NIL ? #{session[:user_id].nil?}"
		puts "CURRENT USER : #{current_user}"
		puts "=" * 25 + 'INDEX' + "=" * 25
		@gossip_arr = Gossip.all
	end

	def create
		@gossip = Gossip.new
		@gossip.title = params[:title]
		@gossip.content = params[:content]
		@gossip.user = current_user 
		@gossip.city = City.all.first
		@gossip.save		
		redirect_to root_path
	end

	def new
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		gossip_params = params.require(:gossip).permit(:title, :content)
		@gossip.update(gossip_params)
		redirect_to(gossip_path(params[:id]))
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end

	private

	def authenticated
		unless current_user
			redirect_to new_session_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
		@gossip_arr = Gossip.all
	end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def presentation
    puts "PRESENTATION DANS TEAM CONTROLLER"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
		puts params[:user]
		user_params = params[:user]
		@user = User.new
		@user.first_name = user_params[:first_name]
		@user.last_name = user_params[:last_name]
		@user.email = user_params[:email]
		@user.password = user_params[:password]
		@user.age = user_params[:age].to_i
		@user.desc = user_params[:desc]
		@user.city = City.all.first
		if @user.save
			login(@user)
			redirect_to gossips_path	
		else
			render :new
		end
		
  end

  def new
		@user = User.new
		# @cities_arr = City.all.map { |each_city| [each_city.name, each_city.id] }
  end

  def edit
  end

  def show
	  @user = User.find(params[:id])
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def show_welcome
    puts params[:first_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def login(user)
		session[:user_id] = user.id
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/affichage.html.erb
<h1>Contact</h1>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Oups !</h1>
    <p class="lead">Vous pouvez nouc contacter directement sur Slack </p>
  </div>
</div>
 

app/views/home/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<div class="container-fluid p-4" style="height: 300px">
	<h1 class="text-center mb-5">TOUS LES GOSSIPS</h1>
	<div class="row justify-content-around align-items-center">
		<% @gossip_arr.each do |gossip| %>
			<div class="col-md-3">
				<div class="card text-center m-2">
					<div class="card-header">
						<%= link_to "#{gossip.title}", gossip_show_path(gossip.id) %>
					</div>
					<div class="card-body">
						<p class="card-text"><%= gossip.content %></p>
						<div class="btn btn-info, text-white bg-dark">by <%=link_to "#{gossip.user.first_name}", user_show_path(gossip.user_id)%> </div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/team/presentation.html.erb
<h1>Présentation de la meilleur équipe THP</h1>



<ul class="list-group">

  <li class="list-group-item list-group-item-primary">Axel Aidan</li> 
  <li class="list-group-item list-group-item-primary">Agathe Plunian</li>
  <li class="list-group-item list-group-item-primary">Amine Amarouche</li>
  <li class="list-group-item list-group-item-primary">Daniel Venera</li>
  <li class="list-group-item list-group-item-primary">Nicolas Chattour</li>
  <li class="list-group-item list-group-item-primary">Mathieu Lasserre</li>

</ul>

app/views/welcome/show_welcome.html.erb
<p>BIENVENUE MON PETIT <%= params[:first_name] %></p>