config/routes.rb
Rails.application.routes.draw do
	# HOMEPAGE
	root 'gossips#index'	

	# ROUTE TEAM & CONTACT
	get '/team', to: 'team#presentation'
	get '/contact', to: 'contact#affichage'

	# ROUTE DYNAMIC PATH
	get '/welcome/:first_name', to: 'welcome#show_welcome'    

	resources :gossips do
		resources :comments, except: [:show, :index]
	end

	resources :users
	resources :cities, except: [:update, :edit, :destroy, :create, :new]
	resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name, presence: true
	validates :zip_code, presence: true

	#LINK USER
	has_many :users
	#LINK GOSSIP
	has_many :gossips
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true

	#LINK USER
	belongs_to :user

	#LINK GOSSIP
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true
	validates :content, presence: true
	belongs_to :user

	#LINK CITY
	belongs_to :city, optional: true

	#LINK COMMENTS
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	#NAMES & AGE
	validates :first_name, presence: true
	validates :last_name, presence: true
	#EMAIL
	validates :email, presence: true,
		uniqueness: true
	#PASSWORD & BCRYPT
	has_secure_password
	validates :password, presence: true,
		length: {minimum: 6}
	#AGE
	validates :age, presence: true

	#LINK GOSSIP
	has_many :gossips
	#LINK CITY
	belongs_to :city, optional: true
	#LINK COMMENT
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
	  @cities_arr = City.all
  end

  def show
	  @city = City.find(params[:id])
	  puts "=" * 60
	  puts @city
	  puts params
	  puts "=" * 60
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticated, only: [:new, :edit]

	def new
		current_gossip = Gossip.find(params[:gossip_id])
		@comment = Comment.new(gossip: current_gossip)
	end

	def create
		comment_params = params[:comment]
		@comment = Comment.new
		@comment.user = current_user 
		@comment.content = comment_params[:content]
		@comment.gossip = Gossip.find(params[:gossip_id])
		@comment.save
		redirect_to gossip_path(@comment.gossip.id)
	end

	def edit
		puts '\n' + '=' * 25 + 'EDIT' + '=' * 25
		puts params
		puts '=' * 25 + 'EDIT' + '=' * 25 + '\n'
		current_gossip = Gossip.find(params[:gossip_id])
		@comment = Comment.find(params[:id]) 
	end

	def update
		puts "\n" + '=' * 25 + 'UPDATE' + '=' * 25
		puts params.inspect
		puts '=' * 25 + 'UPDATE' + '=' * 25 + "\n"
		@comment = Comment.find(params[:id])
		comment_params = params.require(:comment).permit(:content)
		@comment.update(comment_params)
		redirect_to(gossip_path(params[:gossip_id]))
	end

	private

	def authenticated
		unless current_user
			redirect_to new_session_path
		end
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

def affichage
  puts "AFFICHAGE"
end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	before_action :authenticated, except: [:index, :show]
	
	def index
		# DANS SERVEUR AFFICHAGE SESSIONS A CHAQUE RETOUR INDEX
		puts "=" * 25 + 'INDEX' + "=" * 25
		puts "SESSION == NIL ? #{session[:user_id].nil?}"
		puts "CURRENT USER : #{current_user}"
		puts "=" * 25 + 'INDEX' + "=" * 25
		@gossip_arr = Gossip.all
	end

	def create
		@gossip = Gossip.new
		@gossip.title = params[:title]
		@gossip.content = params[:content]
		@gossip.user = current_user 
		@gossip.city = City.all.first
		@gossip.save		
		redirect_to root_path
	end

	def new
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		gossip_params = params.require(:gossip).permit(:title, :content)
		@gossip.update(gossip_params)
		redirect_to(gossip_path(params[:id]))
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end

	private

	def authenticated
		unless current_user
			redirect_to new_session_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
		@gossip_arr = Gossip.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
	end

	def create
		puts "=" * 25 + "CREATE" + "=" * 25
		puts params
		puts "=" * 25 + "CREATE" + "=" * 25

		user = User.find_by(email: params[:email])

		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to gossips_path
		else
			flash.now[:danger] = 'ERROR - email ou mot de passe invalide.'
			render 'new'
		end

		puts "=" * 25 + "CREATE" + "=" * 25
		puts session[:user_id]
		puts "=" * 25 + "CREATE" + "=" * 25
	end

	def destroy
		session.delete(:user_id)
		redirect_to gossips_path
	end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def presentation
    puts "PRESENTATION DANS TEAM CONTROLLER"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
		puts params[:user]
		user_params = params[:user]
		@user = User.new
		@user.first_name = user_params[:first_name]
		@user.last_name = user_params[:last_name]
		@user.email = user_params[:email]
		@user.password = user_params[:password]
		@user.age = user_params[:age].to_i
		@user.desc = user_params[:desc]
		@user.city = City.all.first
		if @user.save
			login(@user)
			redirect_to gossips_path	
		else
			render :new
		end
		
  end

  def new
		@user = User.new
		# @cities_arr = City.all.map { |each_city| [each_city.name, each_city.id] }
  end

  def edit
  end

  def show
	  @user = User.find(params[:id])
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def show_welcome
    puts params[:first_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def login(user)
		session[:user_id] = user.id
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<div class="container">
	<h1>Toutes les Villes</h1>

	<div class="list-group">
		<% @cities_arr.each do |each_city| %>
			<%= link_to "#{each_city.zip_code} - #{each_city.name}", city_path(each_city.id), class: "list-group-item list-group-item-action" %>
		<% end %>
	</div>
</div>

app/views/cities/show.html.erb
<div class="container">


	<h1 class="text-center"><%= @city.name %></h1>
	<h2 class="text-center">Zip Code : <%= @city.zip_code%></h2>
	<h4 class="p-2"><%= "Tous les gossips de cette Ville" %></h3>

	<div class="list-group">

		<% @city.gossips.each do |each_gossip| %>
			<div class="list-group-item">
				<div class="list-group">
					<%= link_to "Titre : #{each_gossip.title}",
						gossip_path(each_gossip.id),
						class: "bg-light list-group-item list-group-item-action" %>

					<div class="list-group-item list-group-item-action">
						<%= "Gossip : #{each_gossip.content}" %>
					</div>

					<%= link_to "Auteur : #{each_gossip.user.first_name} #{each_gossip.user.last_name}",
						user_path(each_gossip.user.id),
						class: "list-group-item list-group-item-action" %>
				</div>
			</div>
		<% end %>

	</div>

</div>

app/views/comments/edit.html.erb
<div class="container">
	<h1 class="text-center">Editer un Commentaire</h1>

	<%= form_for @comment, url: {action: "update"} do |f| %>

		<div class="form-group">
			<label>Contenu :</label>
			<%= f.text_area :content, class: "form-control" %>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-warning btn-lg btn-block">
				Enregistrer les modifications
			</button>
		</div>

	<% end %>

</div>

app/views/comments/new.html.erb
<div class="container">
	<h1>Creer un Commentaire</h1>

	<%= form_for @comment, url: {action: "create"} do |f| %>

		<div class="form-group">
			<label>Commentaire :</label>
			<%= f.text_area :content, class: "form-control" %>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-success">Enregistrer</button>
		</div>

	<% end %>
</div>

app/views/gossip/show.html.erb
<h1>Gossip <%= @gossip.id %></h1>

<h3> <%= @gossip.title %> </h3>
<p> <%= @gossip.content %> </p>
<p> by : <%= link_to "#{@gossip.user.first_name}", user_show_path(@gossip.user_id) %> </p>

app/views/gossips/create.html.erb
<h1>Creer un Gossip</h1>

<form action="<% gossips_path %>" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="text" name="title">
	<input type="text" name="content">
	<input type="submit" value="Creer">
</form>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<div class="container">

	<h1>Editer un Gossip</h1>

	<%= form_for @gossip do |f| %>
		<% @user = @gossip.user %>
		<% @city = @gossip.city %>
		
		<!--
		<div class="form-group">
			<label>Utilisateur :</label>
			<%= f.text_field :user, class: "form-control", placeholder: 'User', value: @user.first_name %> 
		</div>	
		-->

		<div class="form-group">
			<label>Titre :</label>
			<%= f.text_field :title, class: "form-control" %>
		</div>

		<div class="form-group">
			<label>Contenu :</label>
			<%= f.text_area :content, class: "form-control" %>
		</div>	

		<!--
		<div class="form-group">
			<label>Ville :</label>
			<%= f.text_field :city, class: "form-control", placeholder: 'City', value: @city.name %>
			</div>
		-->
		<div class="form-group">
			<button type="submit" class="btn btn-warning btn-lg btn-block">
				Enregistrer les modifications
			</button>
		</div>	

	<% end %>
</div>

app/views/gossips/index.html.erb
<div class="container-fluid p-4 mx-2" style="height: 300px">
	<h1 class="text-center mb-3">TOUS LES GOSSIPS</h1>
	<div class="container text-center">
		<a href="<%= new_gossip_path %>" class="btn btn-primary mb-3">Creer un Gossip</a>
		<a href="<%= cities_path %>" class="btn btn-primary mb-3">Voir toutes les Villes</a>
	</div>
	<div class="d-flex">
		<div class="row justify-content-md-around justify-content-between align-items-center my-1">
			<% @gossip_arr.each do |gossip| %>
				<div class="col-md-6 col-lg-4 col-xl-3 p-1">
					<div class="card text-center mx-auto" style="width: 15rem; height: auto;">
						<div class="card-header">
							<%= link_to "#{gossip.title}", gossip_path(gossip.id) %>
						</div>
						<div class="card-body">
							<p class="card-text"><%= gossip.content %></p>
							<div class="btn btn-info, text-white bg-dark">by <%=link_to "#{gossip.user.first_name}", user_path(gossip.user_id)%> </div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/gossips/new.html.erb
<div class="container">
	<h1 class="text-center m-2">Creer un Gossip</h1>

	<form action="<%= gossips_path %>" method="POST">

		<!-- AUTHENTIFICATION TOKEN -->
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

		<!-- FORM -->
		<div class="form-group">
			<label for="title">Titre</label>
			<input class="form-control" type="text" name="title">
		</div>	

		<div class="form-group">
			<label for="content">Gossip</label>
			<textarea class="form-control" name="content" placeholder="Raconte ta life"></textarea>
		</div>	

		<!-- BUTTON -->
		<div class="form-group">
			<input class="btn btn-success form-control" type="submit" value="Creer">
		</div>	
	</form>
</div>

app/views/gossips/show.html.erb
<div class="container p-2">
	<h3 class="p-2">Gossip <%= @gossip.id %> :</h3>
	<div class="card">
		<div class="card-header">
			<h5 class="card-title"><%= "Titre : #{@gossip.title}" %></h5>
		</div>
		<div class="card-body p-0">
			<div class="list-group list-group-flush">
				<div class="list-group-item list-group-item-action">
					<%= "Gossip : #{@gossip.content}" %>
				</div>
				<%= link_to "Auteur : #{@gossip.user.first_name} #{@gossip.user.last_name}",
					user_path(@gossip.user.id),
					class: "list-group-item list-group-item-action" %>
				<%= link_to "Ville : #{@gossip.city.name}",
					city_path(@gossip.city.id),
					class: "list-group-item list-group-item-action" %>
		</div>
		</div>
	</div>
	<div class="d-flex my-4 justify-content-around">
		<%= link_to "Commenter", new_gossip_comment_path(@gossip.id), class: "btn btn-primary btn-lg" %>
		<% if @gossip.user == current_user %>
			<%= link_to "Editer", edit_gossip_path(@gossip.id), class: "btn btn-warning btn-lg" %>
			<a href="<%= gossip_path(@gossip.id) %>" 
			class="btn btn-danger btn-lg" 
	 data-confirm="Etes-vous sur de vouloir supprimer ce Gossip ?" 
	data-method="DELETE">
	Supprimer
			</a>
		<% end %>
	</div>
	<h3 class="p-2">Commentaires</h3>
	<div class="list-group">
		<% @gossip.comments.each do |each_comment| %>
			<li class="list-group-item list-group-item-action">
				<div class="d-flex justify-content-between">
					<%= link_to "#{each_comment.user.first_name}", user_path(each_comment.user.id), class: "col-1 stretched-link"%>
					<div class="text-center col-9"><%= each_comment.content %></div>	
					<% if each_comment.user.id == current_user.id %>
						<%= link_to "Editer", edit_gossip_comment_path(@gossip.id, each_comment.id), class: "btn btn-warning btn-sm col-1" %>
					<% end %>
				</div>
			</li>
		<% end %>
	</div>
</div>

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container">
	<h1 class="text-center m-2">Inscription</h1>
	<%= form_for @user, url: {action:"create"} do |f| %>

		<!-- FIRST_NAME -->
		<div class="form-group">
			<label>Prenom :</label>
			<%= f.text_field :first_name, class: "form-control" %>
		</div>

		<!-- LAST_NAME  -->
		<div class="form-group">
			<label>Nom de famille :</label>
			<%= f.text_field :last_name, class: "form-control" %>
		</div>

		<!-- EMAIL -->
		<div class="form-group">
			<label>E-mail :</label>
			<%= f.text_field :email, class: "form-control" %>
		</div>

		<!-- CITY
		<div class="form-group">
			<label>Ville :</label>
		</div> -->

		<!-- PASSWORD -->
		<div class="form-group">
			<label>Mot de passe :</label>
			<%= f.text_field :password, type: "password", class: "form-control" %>
		</div>

		<!-- PASSWORD CONFIRMATION -->
		<div class="form-group">
			<label>Mot de passe - CONFIRMATION :</label>
			<%= f.text_field :password_confirmation, type: "password", class: "form-control" %>
		</div>

		<!-- AGE -->
		<div class="form-group">
			<label>Age :</label>
			<%= f.text_field :age, class: "form-control" %>	
		</div>

		<!-- DESCRIPTION -->
		<div class="form-group">
			<label>Description :</label>
			<%= f.text_area :desc, class: "form-control" %>
		</div>

		<!-- BUTTON -->		    
		<div class="form-group">
			<button type="submit" class="btn btn-success btn-lg btn-block">S'inscrire !</button>
		</div>

	<% end %>

</div>

app/views/users/show.html.erb
<div class="container p-2">
	<h3 class="p-2">Profil :</h3>
	<div class="card">
		<div class="card-header">
			<h5 class="card-title"><%= "Nom : #{@user.first_name} #{@user.last_name}" %></h5>
		</div>
		<div class="card-body p-0">
			<div class="list-group list-group-flush">
				<div class="list-group-item list-group-item-action">
					<%= "Age : #{@user.age} ans" %>
				</div>
				<div class="list-group-item list-group-item-action">
					<%= "email : #{@user.email}" %>
				</div>
				<%= link_to "Ville : #{@user.city.name}",
					city_path(@user.city.id),
					class: "list-group-item list-group-item-action" %>
				<div class="list-group-item list-group-item-action">
					<%= "Description : #{@user.desc}" %>
				</div>
			</div>
		</div>
	</div>

	<h3 class="p-2">Gossips de <%= @user.first_name %></h3>

	<div class="list-group">
		<% @user.gossips.each do |each_gossip| %>
			      <div class="list-group-item">
        <div class="list-group">
          <%= link_to "Titre : #{each_gossip.title}",
            gossip_path(each_gossip.id),
            class: "bg-light list-group-item list-group-item-action" %>

          <div class="list-group-item list-group-item-action">
            <%= "Gossip : #{each_gossip.content}" %>
          </div>

          <%= link_to "Auteur : #{each_gossip.user.first_name} #{each_gossip.user.last_name}",
            user_path(each_gossip.user.id),
            class: "list-group-item list-group-item-action" %>
        </div>
      </div>
		<% end %>
	</div>

	<h3 class="p-2">Commentaires de <%= @user.first_name %></h3>
	  <div class="list-group">
    <% @user.comments.each do |each_comment| %>
            <div class="list-group-item">
        <div class="list-group d-flex justify-content-between">
          <div class="list-group-item list-group-item-action">
            <%= "Commentaire : #{each_comment.content}" %>
          </div>

          <%= link_to "Voir le Gossip",
            gossip_path(each_comment.gossip.id),
            class: "list-group-item list-group-item-action" %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>