config/routes.rb
Rails.application.routes.draw do
	# HOMEPAGE
	root 'gossips#index'	

	# ROUTE TEAM & CONTACT
	get '/team', to: 'team#presentation'
	get '/contact', to: 'contact#affichage'

	# ROUTE DYNAMIC PATH
	get '/welcome/:first_name', to: 'welcome#show_welcome'    

	resources :gossips do
		resources :comments, except: [:show, :index]
	end

	resources :users
	resources :cities, except: [:update, :edit, :destroy, :create, :new]
	resources :sessions, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name, presence: true
	validates :zip_code, presence: true

	#LINK USER
	has_many :users
	#LINK GOSSIP
	has_many :gossips
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true

	#LINK USER
	belongs_to :user

	#LINK GOSSIP
	belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true
	validates :content, presence: true
	belongs_to :user

	#LINK CITY
	belongs_to :city, optional: true

	#LINK COMMENTS
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	#NAMES & AGE
	validates :first_name, presence: true
	validates :last_name, presence: true
	#EMAIL
	validates :email, presence: true,
		uniqueness: true
	#PASSWORD & BCRYPT
	has_secure_password
	validates :password, presence: true,
		length: {minimum: 6}
	#AGE
	validates :age, presence: true

	#LINK GOSSIP
	has_many :gossips
	#LINK CITY
	belongs_to :city, optional: true
	#LINK COMMENT
	has_many :comments
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
	  @cities_arr = City.all
  end

  def show
	  @city = City.find(params[:id])
	  puts "=" * 60
	  puts @city
	  puts params
	  puts "=" * 60
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

def affichage
  puts "AFFICHAGE"
end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	before_action :authenticated, except: [:index, :show]
	
	def index
		# DANS SERVEUR AFFICHAGE SESSIONS A CHAQUE RETOUR INDEX
		puts "=" * 25 + 'INDEX' + "=" * 25
		puts "SESSION == NIL ? #{session[:user_id].nil?}"
		puts "CURRENT USER : #{current_user}"
		puts "=" * 25 + 'INDEX' + "=" * 25
		@gossip_arr = Gossip.all
	end

	def create
		@gossip = Gossip.new
		@gossip.title = params[:title]
		@gossip.content = params[:content]
		@gossip.user = current_user 
		@gossip.city = City.all.first
		@gossip.save		
		redirect_to root_path
	end

	def new
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		gossip_params = params.require(:gossip).permit(:title, :content)
		@gossip.update(gossip_params)
		redirect_to(gossip_path(params[:id]))
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end

	private

	def authenticated
		unless current_user
			redirect_to new_session_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
		@gossip_arr = Gossip.all
	end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController

  def presentation
    puts "PRESENTATION DANS TEAM CONTROLLER"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
		puts params[:user]
		user_params = params[:user]
		@user = User.new
		@user.first_name = user_params[:first_name]
		@user.last_name = user_params[:last_name]
		@user.email = user_params[:email]
		@user.password = user_params[:password]
		@user.age = user_params[:age].to_i
		@user.desc = user_params[:desc]
		@user.city = City.all.first
		if @user.save
			login(@user)
			redirect_to gossips_path	
		else
			render :new
		end
		
  end

  def new
		@user = User.new
		# @cities_arr = City.all.map { |each_city| [each_city.name, each_city.id] }
  end

  def edit
  end

  def show
	  @user = User.find(params[:id])
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def show_welcome
    puts params[:first_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def login(user)
		session[:user_id] = user.id
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>The Gossip Project</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="/">Gossip Project</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
				<ul class="navbar-nav mr-auto mt-2 mt-lg-0">

					<% if current_user == nil %>

						<li class="nav-item active">
							<a class="nav-link" href="<%= new_user_path %>">
								Inscription<span class="sr-only">(current)</span>
							</a>
						</li>
						<li class="nav-item active">
							<a class="nav-link" href="<%= new_session_path %>">
								Connexion<span class="sr-only">(current)</span>
							</a>
						</li>

					<% else %>

						<li class="nav-item active">
							<a class="nav-link" href="<%= session_path(session.id) %>" data-method="delete">
								Deconnexion<span class="sr-only">(current)</span>
							</a>					
						</li>

					<% end %>

					<li class="nav-item">
						<a class="nav-link" href="/team">L'équipe</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="/contact">Contact</a>
					</li>

				</ul>
			</div>
		</nav>

		<div class="container-fluid m-3 p-2">
			<div class="list-group px-3">
				<p class="list-group-item text-center p-0">===== A LA CREATION DES GOSSIPS ET DES USERS =====<br>===== LA VILLE EST ATTRIBUEE AUTOMATIQUEMENT =====<br>===== IL S'AGIT DE City.all.first =====</p>
				<p class="list-group-item text-center p-0"><b>RESUME DE SESSION</b></p>
				<p class="list-group-item text-center p-0"><%= "Session en cours : #{session[:user_id]}" %></p>
				<p class="list-group-item text-center p-0"><%= "current_user : #{current_user}" %></p>
			</div>
		</div>

		<div class="container-fluid mt-3 p-2">

			<%= yield %>

			<!--
		 <footer class="page-footer border-top mt-3">
		 <nav class="navbar navbar-light bg-light">
		 <a class="navbar-brand" href="https://github.com/axaidan/TGP_2.git">GitHub Axel Aidan</a>
		 </nav>
		 </footer>
			-->
		</div>
	</body>
</html>